version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    networks:
      - url-shortener-net
    ports:
      - "8089:80"
    restart: always

networks:
  url-shortener-net:
    external: true
